alternate: duck ya

# Site
title: duck ya
subtitle: 呆鸭不呆
description: 个人技术文档
keywords: 欢迎来到呆鸭的笔记空间 ~
author: 小呆
language: zh-CN #中文为 zh-CN
timezone: "Asia/Shanghai" # 东八区时区

social:
  github: https://github.com/zhudaidai416 || github || "#191717"
  # zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"
  # music: https://music.163.com/#/user/home?id=12886823 || cloud-music || "#e60026"
  # weibo: https://weibo.com/amehime || weibo || "#ea716e"
  about: https://zhudaidai416.github.io/myblog/ || address-card || "#3b5998"

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2024
  count: true

# 文章界面统计
post:
  count: true
